"""Isolated, transport-neutral scripted algorithm contracts."""

from ego_annotation.scripted.contracts import (
    AlgorithmRequest,
    AlgorithmResult,
    ApiBackend,
    ContractError,
    FrameTimelineMetadata,
    NativeBatchTrace,
    NativeWorkDescription,
    ScriptBackend,
    StageMetadata,
)
from ego_annotation.scripted.droid_rgbd import (
    ABI_VERSION,
    SEMANTIC_TAG,
    CanonicalKAggregation,
    DepthEvidence,
    DroidContractError,
    DroidNativeSensorDepthAbiPayload,
    DroidPixelGeometry,
    IntrinsicsCandidate,
    PayloadBoundaryRecord,
    PayloadIdentity,
    PayloadIdentityTrace,
    RobustParameterTrace,
    aggregate_canonical_k,
    make_payload_identity_trace,
    normalize_homogeneous,
    pack_native_sensor_depth,
    sensor_disparity_from_stock_gather,
    stock_depthvideo_gather,
)
from ego_annotation.scripted.tensor import CanonicalTensorRef, CanonicalTensorStore, TensorContractError, TensorSpec
from ego_annotation.scripted.worker import PersistentScriptBackend, WorkerProtocolError

__all__ = [
    "ABI_VERSION",
    "AlgorithmRequest",
    "AlgorithmResult",
    "ApiBackend",
    "CanonicalKAggregation",
    "CanonicalTensorRef",
    "CanonicalTensorStore",
    "ContractError",
    "DepthEvidence",
    "DroidContractError",
    "DroidNativeSensorDepthAbiPayload",
    "DroidPixelGeometry",
    "FrameTimelineMetadata",
    "IntrinsicsCandidate",
    "NativeBatchTrace",
    "NativeWorkDescription",
    "PayloadBoundaryRecord",
    "PayloadIdentity",
    "PayloadIdentityTrace",
    "PersistentScriptBackend",
    "RobustParameterTrace",
    "SEMANTIC_TAG",
    "ScriptBackend",
    "StageMetadata",
    "TensorContractError",
    "TensorSpec",
    "WorkerProtocolError",
    "aggregate_canonical_k",
    "make_payload_identity_trace",
    "normalize_homogeneous",
    "pack_native_sensor_depth",
    "sensor_disparity_from_stock_gather",
    "stock_depthvideo_gather",
]
